port: 7880

rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: false
  node_ip: 127.0.0.1

keys:
  devkey: secret-with-at-least-32-characters

room:
  auto_create: true
  empty_timeout: 300
  departure_timeout: 20
  max_participants: 4

logging:
  level: info
  json: false
